//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<decimal> PromedioTA { get; set; }
        public Nullable<decimal> PC2 { get; set; }
        public Nullable<decimal> NotaFinalPC2 { get; set; }
        public string Estado { get; set; }
    }
}
